server:
  port: 9002

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        #配置nacos地址
        server-addr: 172.16.98.130:1111

management:
  endpoints:
    web:
      exposure:
        #默认只公开了/health和/info端点，要想暴露所有端点只需要设置成*
        include: '*'