server:
  port: 83

spring:
  application:
    name: cloud-consumer-service

eureka:
  client:
    #表识不向注册中心注册自己
    register-with-eureka: true
    #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

feign:
  hystrix:
    #如果处理自身的容器就开启，开启方式与生产端不一样
    enabled: true