server:
  port: 9001

elasticsearch:
  host: 127.0.0.1
  port: 9200

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goods?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.chen.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
